### PR TITLE
Client details command

### LINKED ISSUE #68: As an insurance agent, I can see a list of upcoming meetings that I have with each client

### PR DESCRIPTION
**Pull request by zaiahkoh**

### CODE REVIEW

**Comment by zhoube** [comment]
Well done!

**Review by zhoube — COMMENTED** [review]
LGTM!

**Review by Juzzanoob — COMMENTED** [review]
Your code looks fabulous! It follows all of the necessary coding standards we have learnt thus far!

**Review by JodyLorah — COMMENTED** [review]
looks good!

**Pull request merged**
