### PR TITLE
Update EditCommand.java to fix edit bug whereby edit doesn't work wit…

### PR DESCRIPTION
**Pull request by Juzzanoob**
…h only insurance plan edited

### CODE REVIEW

**Comment by Juzzanoob** [comment]
Update EditCommand.java to fix edit bug whereby edit doesn't work if Insurance Plan is the only field of client edited

**Comment by frisciliasultan** [comment]
lgtm

**Review by frisciliasultan — APPROVED** [review]

**Comment by Zaiah0505** [comment]
LGTM

**Review by zaiahkoh — APPROVED** [review]
LGTM

**Pull request merged**
